/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EgParameterJNI */

#ifndef _Included_EgParameterJNI
#define _Included_EgParameterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EgParameterJNI
 * Method:    CalParameter
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_EgParameterJNI_CalParameter
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     EgParameterJNI
 * Method:    Message
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EgParameterJNI_Message
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
